<?php
/** @var MaintainedContentWarning $block */

use Firegento\ContentProvisioning\Block\MaintainedContentWarning;

?>
<?php if ($block->isMaintained()): ?>
    <div class="message-system-short">
        <div class="message-system-wrapper" data-repeat-index="0">
            <div class="message message-warning">
                <?= $block->getMessage() ?>
            </div>
        </div>
    </div>
<?php endif ?>
